name: bazel

on:
  push:
    branches:
      - "**"

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: bazelisk test //... --test_output=errors -k

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bazelisk test //... --test_output=errors -k

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: bazelisk test //... --test_output=errors -k
